/*
# [Operation Name]
Recreate about_content Table

## Query Description: [This operation will permanently delete the existing 'about_content' table and create a new one with the correct structure. This is a critical fix for the "About Us" page errors. All current data in this specific table will be lost and replaced with default content.]

## Metadata:
- Schema-Category: ["Structural", "Dangerous"]
- Impact-Level: ["High"]
- Requires-Backup: [true]
- Reversible: [false]

## Structure Details:
- Drops table: public.about_content
- Creates table: public.about_content
- New Columns: id, section, content, updated_at

## Security Implications:
- RLS Status: [Enabled]
- Policy Changes: [Yes]
- Auth Requirements: [Public read, Admin write]

## Performance Impact:
- Indexes: [Primary Key on id, Unique constraint on section]
- Estimated Impact: [Low]
*/

-- Drop the existing table to ensure a clean slate
DROP TABLE IF EXISTS public.about_content;

-- Create the about_content table with the correct schema
CREATE TABLE public.about_content (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    section text NOT NULL,
    content text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT about_content_pkey PRIMARY KEY (id),
    CONSTRAINT about_content_section_key UNIQUE (section)
);

-- Enable Row Level Security
ALTER TABLE public.about_content ENABLE ROW LEVEL SECURITY;

-- Create policies for about_content
CREATE POLICY "Public can read all about content" ON public.about_content
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Admins can manage all about content" ON public.about_content
AS PERMISSIVE FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Insert initial data
INSERT INTO public.about_content (section, content) VALUES
('mission', 'To foster a generation of compassionate, skilled, and knowledgeable individuals through a vibrant platform of cultural and educational competitions. We aim to nurture talent, promote ethical values, and build a strong sense of community.'),
('vision', 'To be the leading cultural and educational event in the Daawa Sector, recognized for its excellence in promoting artistic expression, intellectual growth, and community engagement, inspiring participants to achieve their full potential.'),
('history', 'Founded over 15 years ago, Muhimmath started as a small local gathering to encourage artistic talents among students. It has since grown into a major annual event, attracting hundreds of participants from across the region. Our journey is a testament to the community''s passion for culture, education, and unity. Each year, we add new events and improve our platform to provide an even more enriching experience for everyone involved.');
