/*
# [Operation Name]
Recreate 'about_content' Table

## Query Description:
This script will completely delete the existing 'about_content' table and recreate it with the correct structure. This is a destructive operation on this specific table, but it is necessary to fix the schema mismatch causing application errors. Any data previously stored in 'about_content' will be lost and replaced with default placeholder text.

## Metadata:
- Schema-Category: "Dangerous"
- Impact-Level: "High"
- Requires-Backup: false
- Reversible: false

## Structure Details:
- Table Dropped: about_content
- Table Created: about_content
- Columns: id, section, content, updated_at

## Security Implications:
- RLS Status: Enabled
- Policy Changes: Yes
- Auth Requirements: None for read, admin for write (handled in app logic)

## Performance Impact:
- Indexes: Primary key on 'id', unique index on 'section'
- Triggers: None
- Estimated Impact: Low
*/

-- Drop the existing table if it exists to ensure a clean slate.
DROP TABLE IF EXISTS public.about_content;

-- Create the table with the correct schema
CREATE TABLE public.about_content (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section text NOT NULL UNIQUE,
    content text,
    updated_at timestamp with time zone DEFAULT now()
);

-- Add comments to the table and columns for clarity
COMMENT ON TABLE public.about_content IS 'Stores the textual content for different sections of the About Us page.';
COMMENT ON COLUMN public.about_content.section IS 'The unique identifier for the content section (e.g., "mission", "vision").';
COMMENT ON COLUMN public.about_content.content IS 'The main text content for the section.';

-- Insert initial placeholder data
INSERT INTO public.about_content (section, content) VALUES
('mission', 'Our mission is to foster a generation of compassionate leaders through education, da''wa, and community service, promoting cultural unity and creative expression.'),
('vision', 'Our vision is to be a leading center for cultural and educational excellence, inspiring individuals to contribute positively to society while upholding strong moral and ethical values.'),
('history', 'From humble beginnings, Muhimmath has grown into a cornerstone of cultural celebration in the Daawa Sector. Over the past 15 years, we have expanded our reach, touching thousands of lives through our events and community projects.');

-- Enable Row Level Security (RLS) for the table
ALTER TABLE public.about_content ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access to everyone
CREATE POLICY "Allow public read access" ON public.about_content
FOR SELECT USING (true);

-- Create a policy to allow authenticated users (admins) to perform all actions
CREATE POLICY "Allow all access for authenticated users" ON public.about_content
FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
