/*
# [Recreate about_content Table]
This migration script drops the existing `about_content` table and recreates it with the correct schema, including the missing `section` column. It also sets up Row Level Security (RLS), an auto-update trigger for the `updated_at` timestamp, and seeds the table with initial data for the mission, vision, and history sections.

## Query Description:
- **Impact:** This operation is destructive as it drops the `about_content` table. Any existing data in this table will be lost. It is being recreated to ensure a clean and correct schema.
- **Safety:** Backup of the `about_content` table is recommended if it contains critical data.
- **Details:** The new table will have `id`, `section`, `content`, `created_at`, and `updated_at` columns. The `section` column will be unique.

## Metadata:
- Schema-Category: "Dangerous"
- Impact-Level: "High"
- Requires-Backup: true
- Reversible: false

## Structure Details:
- **Table Dropped:** `about_content`
- **Table Created:** `about_content`
- **Columns:** `id`, `section`, `content`, `created_at`, `updated_at`
- **Constraints:** `PRIMARY KEY` on `id`, `UNIQUE` on `section`
- **Triggers:** `on_about_content_updated` to handle `updated_at` timestamp.

## Security Implications:
- RLS Status: Enabled
- Policy Changes: Yes. Adds policies for public read access and authenticated write access.
- Auth Requirements: Authenticated users for write operations.

## Performance Impact:
- Indexes: A primary key index and a unique index on `section` will be created.
- Triggers: One `BEFORE UPDATE` trigger is added.
- Estimated Impact: Low, as the table is expected to be small.
*/

-- Drop the existing table to ensure a clean state, if it exists.
DROP TABLE IF EXISTS public.about_content;

-- Create the about_content table with the correct schema.
CREATE TABLE public.about_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section TEXT NOT NULL UNIQUE,
    content TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments for clarity
COMMENT ON TABLE public.about_content IS 'Stores content for the About Us page, like mission, vision, etc.';
COMMENT ON COLUMN public.about_content.section IS 'The unique identifier for the content section (e.g., "mission").';

-- Enable Row Level Security
ALTER TABLE public.about_content ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Public can read about content"
ON public.about_content FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can manage content"
ON public.about_content FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- Create a trigger function to automatically update the updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create a trigger that fires on any update to the about_content table
CREATE TRIGGER on_about_content_updated
BEFORE UPDATE ON public.about_content
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Seed the table with initial data to prevent errors in the admin panel
INSERT INTO public.about_content (section, content)
VALUES
    ('mission', 'To foster a generation of compassionate leaders through education, da''wa, and community service, deeply rooted in faith and dedicated to societal betterment.'),
    ('vision', 'To be a leading center for cultural and intellectual development, inspiring individuals to achieve their full potential and contribute positively to a global community.'),
    ('history', 'Founded over 15 years ago, Muhimmath began as a small community initiative. It has since grown into a major cultural and educational event, attracting hundreds of participants and celebrating the rich heritage of the Daawa Sector.');
